### ISSUE TITLE
Documentation is not up to date

### ISSUE THREAD

**Issue by dglemos** [ejp-rd-vp/FiaB#11]
Hello, 
The documentation on the [main page](https://github.com/ejp-rd-vp/FiaB) does not reflect what is the repo.
At the moment there is only one version of the model 'CDE Version1 Models FiaB' which looks like it was updated to be compatible with version 2 however the docs still mention version 2:

> There are two versions of FiaB. One of them is compatible with Version 1 of the CDE models, the other is compatible with Version 2 CARE-SM models. Version 1 is deprecated and should no longer be used. The installation folder for the CARE-SM FiaB is [CDE Version2 Models FiaB](https://github.com/ejp-rd-vp/FiaB/tree/main/CDE%20Version2%20Models%20FiaB)
> 
> NOTE THAT THE TWO VERSIONS ARE MUTUALLY INCOMPATIBLE! You cannot run them in parallel. They have different Docker components for the transformation, and different YARRRML templates.

and

> If you have never installed FiaB before, you must use the CARE-SM models - Version 1 models are deprecated!!!
> 
> Once you have completed the "Downloading" section of this tutorial, you can run run-me-to-install.sh in the `./CDE Version2 Models FiaB/`` folder

Is CARE-SM-Fiab the one we should use?
Running the script from CARE-SM-Fiab I get the following error:
`./run-me-to-install.sh: 10: Syntax error: "(" unexpected`

**Comment by markwilkinson** [comment]
Indeed, the documentation was much worse than I had expected!  I forgot to update it after the name change of CDE-v2 to CARE-SM, so all links were broken. I think I have fully repaired it now... I hope!

**Comment by dglemos** [comment]
Thank you for the updates!
