### ISSUE TITLE
Invalid IRI in example data

### ISSUE THREAD

**Issue by MalinAhlberg** [ejp-rd-vp/FiaB#12]
When running the data transformations with the provided example files ([preCARE.csv](https://github.com/ejp-rd-vp/FiaB/blob/main/CARE-SM-Fiab/FAIR-ready-to-go/data/preCARE.csv) and [CDE_yarrrml_template.yaml](https://github.com/ejp-rd-vp/CDE-semantic-model-implementations/blob/master/CDE_version_2.0.0/YARRRML/CDE_yarrrml_template.yaml)) I run into an expection about `Invalid IRI found in prefix delcaration: "<https://sio.semanticscience.org/resource/"`, see below

```
yarrrml-rdfizer                  | arguments: /mnt/data/CARE_yarrrml.yaml --outputfile /mnt/data/triples/CARE.nq --serialization nquads
yarrrml-rdfizer                  | mapper arguments: --outputfile /mnt/data/triples/CARE.nq --serialization nquads
yarrrml-rdfizer                  | node:events:491
yarrrml-rdfizer                  |       throw er; // Unhandled 'error' event
yarrrml-rdfizer                  |       ^
yarrrml-rdfizer                  | 
yarrrml-rdfizer                  | Error: Invalid IRI found in prefix delcaration: "<https://sio.semanticscience.org/resource/"
yarrrml-rdfizer                  |     at Reader.error (/yarrrml-parser/node_modules/@graphy/content.ttl.read/main.js:873:9)
```

How can I move forward?

**Comment by markwilkinson** [comment]
Hi! 

Try this:

OK, so two things:  First, it seems that the prefix declaration in the sample YARRRML (both FiaB and in the core CARE-SM model) is incorrect.  You can edit it manually or simply git pull from FiaB and replace the yarrrml with the corrected version: https://github.com/ejp-rd-vp/FiaB/blob/main/CARE-SM-Fiab/FAIR-ready-to-go/data/CARE_yarrrml.yaml
 
Correction is in the "prefix" declarations at the end of the file:  line 484 and line 585:  

  sio: http://semanticscience.org/resource/
  this: http://my.example.com/

Second, Pablo just yesterday released a new version of the transformation engine.  You should update your "caresm" component of the FiaB docker-compose.yml  to be:
 
  caresm:
    image: pabloalarconm/care-sm-toolkit:0.0.3

**Comment by MalinAhlberg** [comment]
Thanks a lot, @markwilkinson ! I managed to import the data now :+1:
