### ISSUE TITLE
Cannot edit Catalog info on my FAIR in a Box

### ISSUE THREAD

**Issue by dglemos** [ejp-rd-vp/FiaB#14]
I have a problem when editing a Catalog or trying to remove it.
If I try to edit any information in the Catalog I get the following error message: "Unable to update entity data"
Now I have a draft Catalog that I want to edit or delete but I cannot do any of those actions.

**Comment by markwilkinson** [comment]
This happens if you modify the SHACL in a way that causes the record to become invalid.

In the latest releases of the FDP client and server, they no longer check for consistency when deleting.

Bump your docker-compose versions to:

  fdp:
    image: fairdata/fairdatapoint:1.16.2

  fdp_client:
    image: fairdata/fairdatapoint-client:1.16.3

That should solve your problem.

Cheers!
