### ISSUE TITLE
Issue finishing the reference configuration

### ISSUE THREAD

**Issue by arjengee** [ejp-rd-vp/FiaB#16]
Have been following the FDP tutorial at https://github.com/ejp-rd-vp/FDP-Reference-Implementation-Configuration. But I’m stuck now at: Create a new record - a Data Service that does visualization (Box-whisker plot).
Did create a new Catalog:
<img width="835" alt="Screenshot 2024-02-08 at 13 59 10" src="https://github.com/ejp-rd-vp/FiaB/assets/55244418/ba624491-a30a-4456-812d-86b7acf8c700">

Not sure what needs to be done at: Once created, that catalog has three kinds of "children", indicated by the tabs: Datasets, Data Services, and Patient Registries. Because when I create a new Child, I don’t understand what to add. We are using the FiaB implementation. Please advice.

**Comment by markwilkinson** [comment]
You don't need to do that section - I only include it to show how you would create a data service, if you needed to (since that's the most complex of all of the object types)
