### ISSUE TITLE
Guidline schema not showing as child resource

### ISSUE THREAD

**Issue by arjengee** [ejp-rd-vp/FiaB#17]
Can you please advice on how to get the Guideline scheme available? Below are the options that we have.

<img width="966" alt="Screenshot 2024-02-08 at 14 04 36" src="https://github.com/ejp-rd-vp/FiaB/assets/55244418/d76f1e3b-4c3f-414e-abf8-2f0870281a50">

**Comment by markwilkinson** [comment]
I have no idea what a "guideline scheme" is...??

**Comment by arjengee** [comment]
This was discussed during the Virtual Office Hours Meeting of today. According to the metadata scheme this should be a type. @HaddadTala, can you please explain?

**Comment by HaddadTala** [comment]
Hi @markwilkinson , 
@arjengee is referring to the ejprd:Guideline resource type in the EJP RD metadata schema (https://github.com/ejp-rd-vp/resource-metadata-schema/blob/master/images/diagram_onboarding_doc/Class%20Diagram%20-%20EJP%20RD%20MM.png)

**Comment by markwilkinson** [comment]
Oh.... we have never created that in any FDP so far....  

I guess you can do so - since Guideline inherits directly from Resource, with no extra features, just create a new class called "Guideline" that is based on the Resource schema.  I have no idea where it should appear in the FDP hierarchy, though, since we have never discussed it in the metadata meetings.  I guess it would be a "child of" Catalog...???  But as I said, we have never discussed it.

**Comment by HaddadTala** [comment]
Hi @markwilkinson, adding @Orphanet and @brunasv to this thread to confirm. 

In the [onboarding document](https://ejprd.sharepoint.com/:b:/r/sites/pillar2-central9/Shared%20Documents/General/3.3_WF_FAIRification/Onboarding%20document/Onboarding%20document%202.0.pdf?csf=1&web=1&e=N9XghM), pages 14-15 explain the classes and how to understand them according to the updated schema diagram. For organizations that have multiple resources, it suggests describing themselves as a catalogue and then describing child classes of guidelines or other resources. @arjengee  and myself discussed this option earlier today for the IMT toolbox and its components. 
Please advise.

**Comment by markwilkinson** [comment]
I will raise the issue at the next Metadata meeting.  It's not that straightforward...

**Comment by markwilkinson** [comment]
This is now done, and in the FDP COnfiguraton instructions
