### ISSUE TITLE
Can't modify metadata through FDP-web-UI when Dgraphdb.external-url is set

### ISSUE THREAD

**Issue by jagerda** [ejp-rd-vp/FiaB#4]
@a-tassoni @markwilkinson 

Hi both!

First of all: @markwilkinson thank you so much that you improved the deployment of multiple FiaBs, e.g. in https://github.com/ejp-rd-vp/FiaB/commit/ac6961621ca1fde4b55fd4fc908335bc2c5805ba - that helps a lot!

Finally, I understood that our problem that we can't edit metadata through FDP-web-UI has nothing to do with shacl-violations like in #1 but rather relates to #2.

Here the instructions for reproduction of the problem:

### 1. prepare reverse proxy
I tested with apache2 with following config:

```
<VirtualHost *:80>

    ServerName localhost
    ErrorLog /var/log/apache2/error_log
    TransferLog /var/log/apache2/access_log

    <LocationMatch /fairdatapoint-euronmd>
      ProxyPass http://localhost:7070
      ProxyPassReverse http://localhost:7070
    </LocationMatch>

    <LocationMatch /graphdb-euronmd>
      ProxyPass http://localhost:7200
      ProxyPassReverse http://localhost:7200
    </LocationMatch>

</VirtualHost>
```

### 2. run the installer
`./run-me-to-install.sh`

Production Installation: `y`
Your permanent GUID (e.g. https://w3id.org/my-organization): `http://localhost/fairdatapoint-euronmd/`
enter a prefix for your components (e.g. euronmd): `euronmd`
Enter the port where your FAIR Data Point will serve (e.g. 7070): `7070`
Enter the port where your GraphDB will serve (e.g. 7200): `7200`
Enter the port where your Beacon2 will serve (e.g. 8000): `8000`
Enter the port that will trigger your RDF transformation (e.g. 4567): `4567`

wait until
Installation Complete!
then `CTRL-C`

### 3. PUBLIC_PATH for fdp-client and start containers from ready-to-go folder

`cd euronmd-ready-to-go`

in docker-compose-euronmd.yml
add PUBLIC_PATH for fdp-client in environment-section e.g.: 
`PUBLIC_PATH: /fairdatapoint-euronmd`

`docker-compose -f docker-compose-euronmd.yml up -d`

to compare ports, images,... `docker ps`
```
CONTAINER ID   IMAGE                                    COMMAND                  CREATED          STATUS          PORTS                                                 NAMES
e81aaa56ef8a   fairdata/fairdatapoint-client:1.15.0     "/docker-entrypoint.…"   29 minutes ago   Up 29 minutes   0.0.0.0:7070->80/tcp, :::7070->80/tcp                 euronmd-ready-to-go_fdp_client_1
4a88919f5bea   fairdata/fairdatapoint:1.15.0            "/bin/sh -c 'java -j…"   29 minutes ago   Up 29 minutes                                                         euronmd-ready-to-go_fdp_1
559da85bb158   markw/cde-box-daemon:0.6.0               "sh entrypoint.sh"       29 minutes ago   Up 29 minutes   127.0.0.1:4567->4567/tcp                              euronmd-ready-to-go_cde-box-daemon_1
5e3bca271761   markw/fdp-metadata-updater:0.0.1         "sh entrypoint.sh"       29 minutes ago   Up 29 minutes                                                         euronmd-ready-to-go_updater_1
7e9fde1b901e   mongo:4.2.3                              "docker-entrypoint.s…"   29 minutes ago   Up 29 minutes   27017/tcp                                             euronmd-ready-to-go_mongo_1
368135fb383a   markw/yarrrml-parser-ejp:latest          "docker-entrypoint.s…"   29 minutes ago   Up 29 minutes                                                         euronmd-ready-to-go_yarrrml_transform_1
2c2dfe137b37   pabloalarconm/ejprd-counting-api:0.0.2   "uvicorn --host 0.0.…"   29 minutes ago   Up 29 minutes   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp             euronmd-ready-to-go_beacon_count_1
8af455a3a642   markw/sdmrdfizer_ejp:0.5.0               "python3 /app/app.py"    29 minutes ago   Up 29 minutes   4000/tcp                                              euronmd-ready-to-go_rdfizer_1
25ec94dda628   ontotext/graphdb:10.1.2                  "/opt/graphdb/dist/b…"   29 minutes ago   Up 29 minutes   0.0.0.0:7200->7200/tcp, :::7200->7200/tcp, 7300/tcp   euronmd-ready-to-go_graphdb_1
```

### 4. check if you can edit metadata on FDP-web-ui now - expect: yes, possible

in a browser, navigate to `http://localhost/fairdatapoint-euronmd/`
if you see "Unable to get data." - just wait ~2 minutes
login as albert.einstein@example.com
test if you can edit metadata on fdp-web-ui now, e.g. change title "My FAIR Data Point" to "My FAIR Data Point 2" 
should work this time
`docker-compose -f docker-compose-euronmd.yml down`

### 5. modify graphdb to solve #2 and start containers again

in docker-compose-euronmd.yml
in section "graphdb" now add Dgraphdb.external-url for graphdb e.g.: 
`command: ["-Dgraphdb.home=/opt/graphdb/home -Dgraphdb.external-url=http://localhost/graphdb-euronmd"]`

```
  graphdb:
    image: ontotext/graphdb:10.1.2
    restart: always
    hostname: graphdb
    command: ["-Dgraphdb.home=/opt/graphdb/home -Dgraphdb.external-url=http://localhost/graphdb-euronmd"]
    ports:
      - 7200:7200
    volumes:
      - euronmd-graphdb:/opt/graphdb/home
    networks:
      - euronmd-default
```

docker-compose -f docker-compose-euronmd.yml up -d

### 6. check if you can still edit metadata on FDP-web-ui now - expect: no
in a browser, navigate to http://localhost/fairdatapoint-euronmd/
again, if you see "Unable to get data." - just wait ~2 minutes
test if you can edit metadata on fdp-web-ui now: http://localhost/fairdatapoint-euronmd/
query will reach graphdb-container but never terminate
you can check in graphdb-query-monitoring on: http://localhost/graphdb-euronmd/monitor/queries (login still default with user admin, pw root)
![image](https://user-images.githubusercontent.com/95087241/217831657-31dc8e07-a978-4b5a-ae30-9b6385173a86.png)

`docker-compose -f docker-compose-euronmd.yml down`

**Comment by markwilkinson** [comment]
This one is much more FDP than FiaB.... I suggest re-posting it to:  https://github.com/FAIRDataTeam/FAIRDataPoint
