### ISSUE TITLE
docker compose version

### ISSUE THREAD

**Issue by francoislamy** [ejp-rd-vp/FiaB#6]
I got an error message while building the shallot docker due to the "name" tag (docker-compose.yml) which was not supported by the version of docker compose (v1.25) previously installed by default ("apt-get" installation). installation of v1.29 solved the issue. 
I am working on ubuntu 20.04 LTS

**Comment by markwilkinson** [comment]
You probably don't need to build the shallot docker yourself... the latest version is in dockerhub.
