### ISSUE TITLE
Cannot install from scratch

### ISSUE THREAD

**Issue by dglemos** [ejp-rd-vp/FiaB#9]
Following the instructions from this section: https://github.com/ejp-rd-vp/FiaB#installing-from-scratch
I run _sh ./run-me-to-install.sh_
```
Is this a production installation, or are you just trying the installer?
Production? [y/n]: n
```
I navigate to http://localhost:7200 but it doesn't work.
http://localhost:7070 also doesn't work.

However, I can manage to have them working if I follow the instructions from this repo: https://github.com/ejp-rd-vp/cde-in-box

Am I missing something from the instructions?

**Comment by markwilkinson** [comment]
The installer is working as far as I know... I used it just yesterday!

Can you give me more information?

cde-in-a-box is deprecated, so I don't recommend you use that...

**Comment by dglemos** [comment]
Thanks for the quick reply!

This is the full log:

```
-e Is this a production installation, or are you just trying the installer?
Production? [y/n]:n
-e 
-e Just trying things out!  Great!  Continuing with some sensible defaults for you...
-e URI: http://localhost:7070
-e Component-prefix: test
-e FDP Port: 7070
-e GraphDB Port: 7200
-e Beacon2 Port: 8000
-e RDF Transformation trigger port: 4567
-e 
mkdir: /Users/dlemos/tmp: File exists
Error response from daemon: network bootstrap_default not found
Error response from daemon: No such container: bootstrap_graphdb_1
Error response from daemon: No such container: metadata_fdp_1
Error response from daemon: No such container: metadata_fdp_client_1
test-graphdb test-fdp-client-assets test-fdp-client-css test-fdp-client-scss test-fdp-server test-mongo-data test-mongo-init
test-graphdb
test-fdp-server
test-fdp-client-assets
test-fdp-client-scss
test-mongo-data
test-mongo-init


-e Creating GraphDB and bootstrapping it - this will take about a minute
-e Go make a nice cup of tea and then come back to check on progress
-e 

sed: 1: "docker-compose-test.yml": extra characters at the end of d command
parsing /Users/dlemos/Documents/work/ejp-rd/docker/FiaB/CDE Version2 Models FiaB/bootstrap/docker-compose-test.yml: yaml: line 10: did not find expected '-' indicator

-e Setting up FAIR Data Point client and server

sed: 1: "docker-compose-test.yml": extra characters at the end of d command
sed: 1: "docker-compose-test.yml": extra characters at the end of d command
sed: 1: "./fdp/application-test.yml": invalid command code .
sed: 1: "./fdp/application-test.yml": invalid command code .
sed: 1: "./fdp/application-test.yml": invalid command code .
parsing /Users/dlemos/Documents/work/ejp-rd/docker/FiaB/CDE Version2 Models FiaB/metadata/docker-compose-test.yml: yaml: line 29: did not find expected '-' indicator

-e Creating a production server folder in  ./test-ready-to-go/

sed: 1: "./test-ready-to-go/dock ...": invalid command code .
sed: 1: "./test-ready-to-go/dock ...": invalid command code .
sed: 1: "./test-ready-to-go/dock ...": invalid command code .
sed: 1: "./test-ready-to-go/dock ...": invalid command code .
sed: 1: "./test-ready-to-go/dock ...": invalid command code .
sed: 1: "./test-ready-to-go/fdp/ ...": invalid command code .
sed: 1: "./test-ready-to-go/fdp/ ...": invalid command code .
sed: 1: "./test-ready-to-go/fdp/ ...": invalid command code .
sed: 1: "./test-ready-to-go/.env": invalid command code .
sed: 1: "./test-ready-to-go/.env": invalid command code .


-e Installation Complete!
-e you now have 10 minutes to test things.
-e If GraphDB is working, you should be able to access it at: http://localhost:7200  (NOTE: this is NOT the port that will serve GraphDB in your production service!  This is only used for the test phase you are currently doing...
-e If Your FAIR Data Point is working, you should be able to access it at: http://localhost:7070

-e NOTE: If you see the message:

-e                  unable to get data 

-e       in your FAIR Data Point web page, 
-e       it is likely because GraphDB hasn't finished setting itself up.
-e       wait until you are able to connect to http://localhost:7200 and then try again!
-e       It can take up to a minute after GraphDB comes alive before the FDP completes its initialization...

-e For further instructions and tests, read the documentation on the FAIR-in-a-box GitHub page

-e You can stop this test phase at any time with CTRL-C, then wait for the docker images to shut down cleanly before continuing
```
There are a few parsing errors.

**Comment by markwilkinson** [comment]
Gosh... that's nothing but errors!  

A bit more detail:  Which operating system are you on?   The errors suggest that you are not using bash... how are you invoking the installer?

can you try explicitly using bash?

/bin/bash run-me-to-install.sh

**Comment by dglemos** [comment]
I'm running on macOS 13.4.1
Docker version 24.0.6, build ed223bc
Docker Compose version v2.22.0-desktop.2

**Comment by markwilkinson** [comment]
Hmmmm.... I've never followed anyone installing on a Mac, and I have never touched one myself, so... I'm not sure what to suggest.   It's definitely not executing the bash commands the way that Linux does, and so nothing is getting installed at all as far as I can see from your logs.

Did you try invoking bash directly?

**Comment by dglemos** [comment]
Yes, tried with your suggestion. I get the exact same errors.
I'm going to try on a different machine which is not macOS.

**Comment by markwilkinson** [comment]
Sounds good!  I just ran it for a non-production installation and both graphdb and the FDP came up on localhost, so... the installer is working correctly on Linux :-)  (I know that doesn't help you!)

**Comment by markwilkinson** [comment]
I just did a bit of searching and, indeed, there are differences between bash in MacOS vs. Linux related to some commands in the installer:
`
The major problem is that the MacOS coreutils are FreeBSD-based while the utilities you are used to are most likely from the GNU project. The FreeBSD coreutils are not always compatible with the GNU coreutils. There are performance and behavioral differences between the GNU and FreeBSD versions of [sed](http://forums.freebsd.org/showthread.php?p=207335), [grep](http://lists.freebsd.org/pipermail/freebsd-current/2010-August/019310.html), [ps](https://serverfault.com/questions/324945/what-is-the-os-x-bsd-equivalent-of-the-gnu-ps-auxf-command), and [other utilities](https://unix.stackexchange.com/questions/79355/what-are-the-main-differences-between-bsd-and-gnu-linux-userland/79357#79357).
  You can install the GNU coreutils but they have g- prefixes (e.g. gcat for cat). It's [not a good idea](https://apple.stackexchange.com/questions/69223/how-to-replace-mac-os-x-utilities-with-gnu-core-utilities) to replace the MacOS coreutils with the GNU coreutils.`

**Comment by dglemos** [comment]
It worked on a Linux machine!
The following ports are working:
- http://localhost:7200/ (GraphDB)
- http://localhost:7070/ (FDP)

I don't really understand this section https://github.com/ejp-rd-vp/FiaB#implementing-beacon2-and-other-services
What exactly is this Beacon2?

**Comment by markwilkinson** [comment]
Happy that you got it working!

Beacon2 is a query interface designed specifically for EJP.  It allows privacy-preserving queries over the data (e.g. patient counts).  It is entirely optional.

**Comment by dglemos** [comment]
Thanks for the clarification.

Unfortunately I hit another problem.
In this step https://github.com/ejp-rd-vp/FiaB#find-the-folder-with-your-final-server-config-ready-to-go
After copying the files to ~/SERVERS/
I run the command: `docker-compose -f docker-compose-ensemblvep.yml up`

I got an error:
```
Status: Downloaded newer image for pabloalarconm/ejprd-counting-api:0.0.2
Creating ensemblvep-ready-to-go_hefesto_1      ... done
Creating ensemblvep-ready-to-go_beacon_count_1 ... done
Creating yarrrml-rdfizer                       ... done
Creating ensemblvep-ready-to-go_updater_1      ... done
Creating ensemblvep-ready-to-go_graphdb_1      ... done
Creating ensemblvep-ready-to-go_mongo_1        ... done
Creating cde-box-daemon                        ... done
Creating ensemblvep-ready-to-go_fdp_1          ... done
Creating ensemblvep-ready-to-go_fdp_client_1   ... 
Creating ensemblvep-ready-to-go_fdp_client_1   ... error

ERROR: for ensemblvep-ready-to-go_fdp_client_1  Cannot start service fdp_client: driver failed programming external connectivity on endpoint ensemblvep-ready-to-go_fdp_client_1 (85de725821a2c58dcc3a0719ad7d2a346c3f94f29dcf6a825e4e7768c081298c): Bind for 0.0.0.0:8080 failed: port is already allocated

ERROR: for fdp_client  Cannot start service fdp_client: driver failed programming external connectivity on endpoint ensemblvep-ready-to-go_fdp_client_1 (85de725821a2c58dcc3a0719ad7d2a346c3f94f29dcf6a825e4e7768c081298c): Bind for 0.0.0.0:8080 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```
Port 8080 is the one I defined for the FAIR data point. The ports 8080 and 8200 are running since I created my server.
Port 8200 is for the GraphDB as far as I understand graphdb created successfully.
